### ISSUE TITLE
Security Concerns For Users

### ISSUE THREAD

**Issue by joncodo** [aviaviavi/scarf#29]
## Concerns

The only problem I have with this is the security aspect. I think users will not know the scarf domain and will be concerned as to what they are pulling. I also think that it puts our user's security in the hands of scarf. If something goes wrong there, all our users could download viruses or fail to get our image.

I am worried that the benefits of gathering data on users that pull our images will be counter balanced by less users adopting our software from this concern.

@aviaviavi can you help me address this business issue?

**Comment by aviaviavi** [comment]
Hi @joncodo Security is crucial to Scarf, so we can definitely accommodate these concerns. 

> I think users will not know the scarf domain and will be concerned as to what they are pulling

Your gateway package is currently using a Scarf-powered domain (joncodo.gateway.scarf.sh), but you can also connect your own domain so it's not a Scarf URL at all (something like, eg. containers.meri.co, or whatever you'd like). That way, your users know they are getting the images from a place that your company has authorized. 

> If something goes wrong there, all our users could download viruses

True, but this is the case on any registry already whether or not you're using Scarf. Trusting content based on the URL alone is not a recommended package management strategy, regardless of using a gateway service like Scarf or otherwise. The best way to help your users ensure they are pulling the correct containers, is to upload signatures that your users could verify. Docker has built-in tooling for this, and they can be used in tandem with Scarf.

> ...or fail to get our image.

Making your images available through Scarf does indeed mean that the gateway URL will stop working in the event of a Scarf outage. 2 mitigating factors there:

- Our backend infrastructure is globally distributed and built to be highly reliable and very fast. The gateway itself is very very simple and doesn't need much updating, the complexity lies in the downstream data analytics pipeline, which does not impact gateway availability.
- If Scarf does go down, your containers are still available directly from Docker Hub (or whatever registry you're on). We're not replacing your existing distribution channel, merely adding a new one. In fact, Scarf can even keep your images online if your backing registry itself goes down!  

Happy to discuss in more detail over a call, let me know.
